In [19]:
import numpy as np
import csv
import os

In [11]:
os.chdir('/data/ubcitar/aweber/PythonNotebook/2017CodingAdventCalendar/')
for x in os.listdir('.'):
    print(x)

Day2input.txt
.git
Day2.ipynb
README.md
Day1.txt
.ipynb_checkpoints
Day2.txt
Day1.ipynb


In [21]:
my_data = list(csv.reader(open('Day2input.txt', 'rt'), delimiter='\t'))

In [38]:
myarray = np.asarray(my_data)

In [41]:
myarray[0][15]

'2502'

In [42]:
shape = np.shape(myarray)
shape[1]

16

In [51]:
myarray = myarray.astype(int)

In [52]:
max(myarray[0])

2593

In [58]:
newarray = np.zeros(shape=(16,3))
for i in range(shape[1]):
    maxtmp = max(myarray[i])
    mintmp = min(myarray[i])
    diffmaxmin = maxtmp-mintmp
    newarray[i]=[maxtmp,mintmp,diffmaxmin]
    print(maxtmp,mintmp,diffmaxmin)

2593 125 2468
6188 149 6039
512 102 410
2898 200 2698
3999 170 3829
313 69 244
1288 45 1243
3227 93 3134
494 40 454
2615 81 2534
3003 214 2789
3456 216 3240
2798 157 2641
3786 99 3687
7219 178 7041
2331 112 2219


In [59]:
newarray[0][2]

2468.0

In [60]:
np.sum(newarray,axis=0)

array([ 46720.,   2050.,  44670.])

In [61]:
myarray[0]

array([ 626, 2424, 2593,  139, 2136,  163, 1689,  367, 2235,  125, 2365,
        924,  135, 2583, 1425, 2502])

In [69]:
sorted(myarray[0], reverse=True)

[2593,
 2583,
 2502,
 2424,
 2365,
 2235,
 2136,
 1689,
 1425,
 924,
 626,
 367,
 163,
 139,
 135,
 125]

In [137]:
shape

(16, 16)

In [155]:
newarray = np.zeros(shape=(shape[0],3))
for i in range(shape[0]):
    
    sort = sorted(myarray[i], reverse=True)
    for j in range(shape[1]):
        tmp = sort[j]%sort[(j+1):16]
        if len(tmp[tmp==0]) == 1:
            indx = np.where(tmp == 0)
            indx = int(indx[0]) +j+1
            newarray[i]=[sort[j],sort[indx],int(sort[j]/sort[indx])]
            break
        
print(newarray.astype(int))
np.sum(newarray,axis=0)

[[2502  139   18]
 [5430  181   30]
 [ 350  175    2]
 [2772  231   12]
 [3759  179   21]
 [ 208  104    2]
 [1150   50   23]
 [2813   97   29]
 [ 444   74    6]
 [2346  102   23]
 [2782  214   13]
 [3456  216   16]
 [2678  206   13]
 [3675  105   35]
 [6670  230   29]
 [2275  175   13]]


array([ 43310.,   2478.,    285.])